### ISSUE TITLE
get_pip script old, doesn't work behind proxy

### ISSUE THREAD

**Issue by amaltson** [poise/python#136]
The [get-pip.py](https://bootstrap.pypa.io/get-pip.py) script has been updated a bunch since the current bootstrap script. I'm finding it doesn't correctly install behind a proxy when using `http_proxy` ENV variable. Using the latest get-pip everything works as expected. The current `get-pip.py` script is confused with the following:

```
get-pip.py run on Fri Jan 23 14:13:58 2015
Downloading/unpacking pip
  Getting page https://pypi.python.org/simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: connection error: hostname '<proxy server>' doesn't match either of 'www.python.org', 'python.org', 'pypi.python.org', 'docs.python.org', 'testpypi.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'packaging.python.org', 'pythonhosted.org', 'www.pythonhosted.org', 'test.pythonhosted.org', 'us.pycon.org', 'id.python.org'
  Will skip URL https://pypi.python.org/simple/pip/ when looking for download links for pip
  Getting page https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/: connection error: hostname '<proxy server>' doesn't match either of 'www.python.org', 'python.org', 'pypi.python.org', 'docs.python.org', 'testpypi.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'packaging.python.org', 'pythonhosted.org', 'www.pythonhosted.org', 'test.pythonhosted.org', 'us.pycon.org', 'id.python.org'
  Will skip URL https://pypi.python.org/simple/ when looking for download links for pip
  Cannot fetch index base URL https://pypi.python.org/simple/
  URLs to search for versions for pip:
  * https://pypi.python.org/simple/pip/
  Getting page https://pypi.python.org/simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: connection error: hostname '<proxy server>' doesn't match either of 'www.python.org', 'python.org', 'pypi.python.org', 'docs.python.org', 'testpypi.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'packaging.python.org', 'pythonhosted.org', 'www.pythonhosted.org', 'test.pythonhosted.org', 'us.pycon.org', 'id.python.org'
  Will skip URL https://pypi.python.org/simple/pip/ when looking for download links for pip
  Could not find any downloads that satisfy the requirement pip
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for pip
Exception information:
Traceback (most recent call last):
  File "/tmp/unpacker-UNoDRZ-scratchdir/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/unpacker-UNoDRZ-scratchdir/pip/commands/install.py", line 274, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/unpacker-UNoDRZ-scratchdir/pip/req.py", line 1166, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/tmp/unpacker-UNoDRZ-scratchdir/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pip
```

**Comment by chantra** [comment]
@amaltson , until PR#142 get merged, you can use https://github.com/chantra/python/tree/fix_get-pip.py

**Comment by amaltson** [comment]
Thanks, I ended up updating the file myself, but I'll watch the PR. Thanks.

**Comment by coderanger** [comment]
https://github.com/poise/poise-python allows giving a URL to a local copy of get-pip.py.
