### ISSUE TITLE
execute[install-pip] fails on Debian 8 #SSLv3

### ISSUE THREAD

**Issue by rmoriz** [poise/python#162]
reason: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

log: 
```shell
      Recipe: python::pip
         * cookbook_file[/tmp/kitchen/cache/get-pip.py] action create (up to date)
       * execute[install-pip] action run
           
           ================================================================================
           Error executing action `run` on resource 'execute[install-pip]'
           ================================================================================
           
       Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of   /usr/bin/python get-pip.py
        ----
           STDOUT: 
           STDERR: Traceback (most recent call last):
             File "get-pip.py", line 21529, in <module>
        do_exec(entry, locals())
             File "<string>", line 1, in do_exec
             File "<string>", line 2, in <module>
             File "/tmp/unpacker-GcT6oV-scratchdir/pip/__init__.py", line 11, in <module>
             File "/tmp/unpacker-GcT6oV-scratchdir/pip/vcs/mercurial.py", line 9, in <module>
             File "/tmp/unpacker-GcT6oV-scratchdir/pip/download.py", line 22, in <module>
             File "/tmp/unpacker-GcT6oV-scratchdir/pip/_vendor/requests/__init__.py", line 53, in <module>
             File "/tmp/unpacker-GcT6oV-scratchdir/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
           AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
           ---- End output of   /usr/bin/python get-pip.py
            ----
           Ran   /usr/bin/python get-pip.py
            returned 1
           
           Resource Declaration:
       ---------------------
           # In /tmp/kitchen/cookbooks/python/recipes/pip.rb
       
       
            43:   cwd Chef::Config[:file_cache_path]
            44:   command <<-EOF
            45:   #{node['python']['binary']} get-pip.py
            46:   EOF
            47:   not_if { ::File.exists?(pip_binary) }
            48: end
            49: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/python/recipes/pip.rb:42:in `from_file'
           
           execute("install-pip") do
             action "run"
         retries 0
             retry_delay 2
             default_guard_interpreter :execute
             command "  /usr/bin/python get-pip.py\n"
             backup 5
             cwd "/tmp/kitchen/cache"
             returns 0
         declared_type :execute
             cookbook_name :python
             recipe_name "pip"
             not_if { #code block }
           end

```

**Comment by coderanger** [comment]
Should be taken care of in https://github.com/poise/poise-python
