### ISSUE TITLE
Deprecated features used with Chef: 12.5.1

### ISSUE THREAD

**Issue by tiago-cruz-movile** [poise/python#169]
Using  version "1.4.6", I've got:

```
Deprecated features used!
  version nil currently does not overwrite the value of version.
 This will change in Chef 13, and the value will be set to nil instead.
 Please change your code to explicitly accept nil using "property :version, [MyType, nil]", or stop setting this value to nil. at 3 locations:
    - /var/chef/cache/cookbooks/python/recipes/pip.rb:52:in `block in from_file'
    - /var/chef/cache/cookbooks/python/recipes/virtualenv.rb:25:in `block in from_file'
    - /var/chef/cache/cookbooks/python/providers/pip.rb:98:in `load_current_resource'
```

I saw the deprecated warning, so i'm not sure if it will be fixed :)

Thanks anyway!

**Comment by coderanger** [comment]
The cookbook as a whole is deprecated, so no.
