### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by jenssegers** [poise/python#170]
I'm currently getting this error when installing pip on Debian 7:

```
[2015-12-27T15:41:31-05:00] ERROR: execute[install-pip] (python::pip line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of   /usr/bin/python get-pip.py
 ----
STDOUT: 
STDERR: Traceback (most recent call last):
  File "get-pip.py", line 21529, in <module>
    do_exec(entry, locals())
  File "<string>", line 1, in do_exec
  File "<string>", line 2, in <module>
  File "/tmp/unpacker-rbXmOj-scratchdir/pip/__init__.py", line 11, in <module>
  File "/tmp/unpacker-rbXmOj-scratchdir/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/unpacker-rbXmOj-scratchdir/pip/download.py", line 22, in <module>
  File "/tmp/unpacker-rbXmOj-scratchdir/pip/_vendor/requests/__init__.py", line 53, in <module>
  File "/tmp/unpacker-rbXmOj-scratchdir/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
---- End output of   /usr/bin/python get-pip.py
```

**Comment by jenssegers** [comment]
I did not know this repo was deprecated.
